version: '3'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

volumes:
  mongodb_data_container: